### PR TITLE
Fixed broken functions, quickstartified

### PR DESCRIPTION
**Pull request by wiazur**
## Purpose
The Read Batch File functions were broken (new constructor), so those were fixed. Also cleaned up a lot of comments, changed them to the quickstart standard. Typos and other missing API print statements were added. A few shared variables are now at the top. Also renamed several variables to avoid same-names in other examples of the quickstart.

## Does this introduce a breaking change?
The constructor for Read Batch File is different.
```
[x ] Yes
[ ] No
```

### CODE REVIEW

**Comment by wiazur** [comment]
@PatrickFarley If you get a chance to review soon, that'd be great. Some users are noticing the broken code of the old version and letting us know. Thanks.

**Comment by PatrickFarley** [comment]
Hi @wiazur , could you recover the snippet_remoteimage tags? The tags got deleted when you moved that code.

**Comment by wiazur** [comment]
Hi @PatrickFarley  did you get my latest email? I sent an explanation of the changes made and why. Here it is:

Items changed:

-	mostly comments to adhere to our quickstart standard
-	the read_batch_file() function (both local and remote examples) due to the CV SDK update change
-	took out any print statements referencing the files (not really needed, especially since quickstart is already very long)
-	moved shared variables to the top (standard our team decided on). Unique files/URLs used once remain in the example
-	corrected typos or missing results

1.	The main thing you want to check is that the tags are still valid. 
2.	I took out one tag entirely, only because it was to print a file name. This was the <snippet_remoteimage>, line 69 and 73 of the old version. 
3.	The shared variables at the top, you might want new tags for those?
4.	I wasn’t sure if you wanted the existing tags to include all the comments at the top of each example or not, so move them below if needed. The old ones did include the comments, but the structure is slightly different now, so double check each example tag is in the right place.

Let me know if anything else comes up, thanks!

**Comment by PatrickFarley** [comment]
@wiazur That snippet included the variable definition (not just the print statement), which we need in the quickstart, so please add the tags around the same variable definition in its new location.

**Comment by wiazur** [comment]
Thanks @PatrickFarley good call, I added it back in. As soon as you approve, I'll publish. Someone already created a new PR for this issue, so wanted to get this published ASAP. Thanks!

**Pull request merged**
