### PR TITLE
Update application_quickstart.py

### PR DESCRIPTION
**Pull request by v-jaswel**
## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by diberry** [comment]
@v-jaswel Thank you for updating this - I was wondering if you can add an ML entity example? You might want to re-read the top text describing what is going on. I think it doesn't match the code.

**Comment by v-jaswel** [comment]
I've updated this as follows.
- Rewrote the comments at the top - please let me know if they are clearer now.
- Changed the add_entities function so that the Flight entity now has children, which makes use of other entities added previously (number, datetimeV2, etc).
- For some reason, I cannot add instances of entities I've created (e.g. Class, Location) as children of another entity like Flight. That behavior is also present at the REST API level. I have a mail out to Carol Hanna asking about this.

**Comment by diberry** [comment]
@v-jaswel Are you done with changes to this sample? I want to start working on the quickstart if you are.

**Comment by v-jaswel** [comment]
@diberry I am indeed done updating this sample, thank you.

**Pull request closed without merging**
