### PR TITLE
Added thumbnail example

### PR DESCRIPTION
**Pull request by wiazur**
Computer Vision - Face

Renamed the recognize text example to Read Batch File (both local and remote), so not to be confused with an API call that is name recognize_text(). No code was changed. There is also the Recognize text for OCR that was left as is, since it does not use the read_batch_file() API call.

## Does this introduce a breaking change?
```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Comment by wiazur** [comment]
@PatrickFarley please double check snippet tags before I merge. Thanks.

**Comment by PatrickFarley** [comment]
@wiazur This looks fine to me. I'm curious why you changed the capitalization scheme. We always use sentence-style capitalization in the docs.

**Comment by wiazur** [comment]
Hi @PatrickFarley, I wanted to make a distinction that matches the API call name a bit better. This way if a user scans the quickstart, the capitalized words stand out more and they can associate that with the API name, instead of wading through the entire description of the function. So, just an ease of use reason. That's also why I do the print statements in all caps for the results. In the docs you have paragraph headings and the like, so it'd be much easier to separate.

**Comment by PatrickFarley** [comment]
Ok, you can go ahead and merge then

**Pull request merged**
